// =======================================================================
// Module:      Arithmetic Logic Unit (ALU)
// Project:     Ripple-32
// Description: The ALU performs arithmetic and logical operations 
//              based on the control signals generated by the control unit.
// =======================================================================

module alu (
  input  wire [31:0] a,           // Operand A
  input  wire [31:0] b,           // Operand B
  input  wire [3:0]  alu_control, // ALU operation control signal
  output reg  [31:0] result,      // ALU result
  output reg         zero,        // Zero flag
  output reg         carry,       // Carry flag
  output reg         overflow     // Overflow flag
); 

// TODO: Implement the ALU operations based on the alu_control signal

localparam ADD  = 4'b0000;
localparam SUB  = 4'b0001;
localparam SLL  = 4'b0010;  
localparam SLT  = 4'b0011;
localparam SLTU = 4'b0100;
localparam XOR  = 4'b0101;
localparam SRL  = 4'b0110;  // shift right logical
localparam SRA  = 4'b0111;  // shift right arithmetic
localparam OR   = 4'b1000;
localparam AND  = 4'b1001;


// 33-bit temporary variable for capturing carry
reg [32:0] ans;

always @(*) begin
  // Set default values to 0
  carry    = 1'b0;
  overflow = 1'b0;
  ans      = 33'b0;

  case (alu_control)
    ADD: begin
      ans      = {1'b0, a} + {1'b0, b};
      result   = ans[31:0];
      carry    = ans[32];
      overflow = (a[31] == b[31]) && (result[31] != a[31]);
    end

    SUB: begin
      ans      = {1'b0, a} - {1'b0, b};
      result   = ans[31:0];
      carry    = ans[32];
      overflow = (a[31] != b[31]) && (result[31] != a[31]);
    end

    AND: result = a & b; 
    OR:  result = a | b;
    XOR: result = a ^ b;

    SLL: result = a << b[4:0];
    SRL: result = a >> b[4:0]; 
    SRA: result = $signed(a) >>> b[4:0]; 

    SLT: result = ($signed(a) < $signed(b)) ? 32'd1 : 32'd0;  //set less than
    SLTU:result = (a < b) ? 32'd1 : 32'd0;                    // set less than (unsigned)

    default: result = 32'b0;
  endcase

  // Zero flag
  zero = (result == 32'b0);
end
endmodule