// =======================================================================
// Module:      Arithmetic Logic Unit (ALU)
// Project:     Ripple-32
// Description: The ALU performs arithmetic and logical operations 
//              based on the control signals generated by the control unit.
// =======================================================================

module alu (
  input  wire [31:0] src_a,           // Operand A
  input  wire [31:0] src_b,           // Operand B
  input  wire [3:0]  alu_control,     // ALU operation control signal
  output reg  [31:0] alu_result,      // ALU result
  output reg         zero             // Zero flag
);
 
  // ALU Operations
  always @(*) begin
    case (alu_control)
      4'b0000: alu_result = src_a + src_b;                 // ADD
      4'b1000: alu_result = src_a - src_b;                 // SUB
      4'b0100: alu_result = src_a ^ src_b;                 // XOR
      4'b0110: alu_result = src_a | src_b;                 // OR
      4'b0111: alu_result = src_a & src_b;                 // AND
      4'b0001: alu_result = src_a << src_b[4:0];           // SLL
      4'b0101: alu_result = src_a >> src_b[4:0];           // SRL
      4'b1101: alu_result = $signed(src_a) >>> src_b[4:0]; // SRA
      default: alu_result = 32'b0;
    endcase

    zero = (alu_result == 32'b0) ? 1'b1 : 1'b0; // Set zero flag
  end


endmodule